apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-irisv2"
spec:
  predictor:
    minReplicas: 1
    scaleTarget: 3
    scaleMetric: concurrency
    model:
      modelFormat:
        name: sklearn
      protocolVersion: v2
      runtime: kserve-sklearnserver
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
      resources:
        limits:
          cpu: "3"
          memory: 3Gi
        requests:
          cpu: "200m"
          memory: 700Mi
