apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "torchserve"
spec:
  predictor:
    minReplicas: 1
    scaleTarget: 3
    scaleMetric: concurrency
    model:
      modelFormat:
        name: pytorch
      storageUri: gs://kfserving-examples/models/torchserve/image_classifier/v1
      resources:
        limits:
          cpu: "3"
          memory: 3Gi
        requests:
          cpu: "200m"
          memory: 700Mi

