apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "flower-sample"
spec:
  predictor:
    minReplicas: 1
    scaleTarget: 3
    scaleMetric: concurrency
    model:
      modelFormat:
        name: tensorflow
      storageUri: "gs://kfserving-examples/models/tensorflow/flowers"
      resources:
        limits:
          cpu: "3"
          memory: 3Gi
        requests:
          cpu: "200m"
          memory: 700Mi
